#!/usr/bin/env bash
# 404 Not Found Page

# Install Nginx
apt-get update
apt-get install nginx -y

# Get the hostname of the server
hostname=$(hostname)

# Configure Nginx to add a custom HTTP header
echo 'add_header X-Served-By "'$hostname'";' >> /etc/nginx/nginx.conf

# Restart Nginx to apply the configuration changes
systemctl restart nginx
